### ISSUE TITLE
Gossip protocol

### ISSUE THREAD

**Issue by p3rsik** [SkyProtocol-org/skyprotocol#12]
Implement the go-libp2p Gossip protocol in the current node example.

**Comment by fare** [comment]
Can you describe your proposed protocol at the moment?

**Comment by p3rsik** [comment]
This is a long-standing issue which will be used for discussions about the code in the `issue-12/gossip-protocol` branch. 

The idea of the issue, is to implement something similar to go-libp2p Gossip protocol for our pubsub implementation.

Current plan:
- [x] - implement basic node design
- [x] - make it modular and easily extendable
- [ ] - implement data marshaling using the @fare's type descriptors
- [ ] - implement basic pubsub functionality

The plan will be modified as needed during the development and subsequent discussions.
